# Generated by Django 5.2.6 on 2025-12-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('song', models.TextField(blank=True, max_length=20)),
                ('music_type', models.TextField(max_length=20, null=True)),
                ('year_of_song', models.CharField(max_length=20)),
            ],
        ),
    ]
