# Generated by Django 5.2.6 on 2025-12-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('album', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.PositiveBigIntegerField()),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('audio_file', models.FileField(upload_to='audios/')),
            ],
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
