# Generated by Django 5.2.6 on 2025-12-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_song_delete_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='year',
            field=models.CharField(max_length=255),
        ),
    ]
