# Generated by Django 5.2.6 on 2025-12-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_alter_song_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='album',
            new_name='Album',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artist',
            new_name='Artist',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='audio_file',
            new_name='Audio_file',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='tittle',
            new_name='Tittle',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='year',
            new_name='Year_of_release',
        ),
        migrations.RemoveField(
            model_name='song',
            name='cover_photo',
        ),
    ]
